### ISSUE TITLE
should we have the locations and/or subjects on off options?

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/collectionbuilder-gh#20]
This is for both gh and the skins: 

Having an on/off for the locations field just messed me up for awhile. I feel like we should just expect the user to edit the config-nav to determine which pages show up and which don't. 

I guess there might be some need to limit the build time this way? 

If that is the case, let's have the default theme.yml always have them turned on. 

Also, you still have to delete the about from the nav so maybe remove that on/off as well?

**Comment by owikle** [comment]
Evan and I just tested this and switching it to "off" does reduce the build time... slightly. It is confusing that the user has to edit both the theme and config-nav, but documentation explains this, and our tutorial videos show both steps in one video. What if we make the comments clearer in the theme to explain this extra step? 

I think subjects should be on and locations off, but it seems worth removing the on/off for the about page for gh because we've already taken it out of the skin too.

**Comment by evanwill** [comment]
- with subjects/locations, would we still even have them as separate pages when its updated to "cloud" page? Then the on/offs become irrelevant since the config of the cloud will drive what gets built.
- the about page on/off just removes the button on the info-graphic layout with link to the about page (comes from collectionbuilder-cdm-template where @dcnb insisted it was necessary!)

**Comment by dcnb** [comment]
I think we could change the logic to remove the button to be based on the
nav-config. My reasoning behind this and many other of these decisions is
to make sure the sites that are auto generated are as problem free as
possible. Taking unnecessary options away from the user and anticipating
problems when deploying will help the sites look better and prevent users
from abandoning the tool because they can't get certain options fixed.

I think locations should be left on. and that we should indicate in a
trouble shooting doc and the documentation that turning it off will reduce
build time. That's an advanced user issue -- I think we should be designing
for the less advanced -- one who will be more and more encouraged to use
the tool if everything just works.

**Comment by evanwill** [comment]
For about on/off, yeah, probably better to use config-nav--i just a bit nervous about relying on config-nav (currently used for the data markup and downloads too), since it hides away configuration which is a bit difficult to figure out--if you just changed your about page or map page name it breaks things, and it wouldn't be very obvious why. we can document it, but obviously... anyway, not sure the best solution, just trying to think how to balance the hiding and exposing options.

**Comment by dcnb** [comment]
I see the issue ...

Let's get a development meeting for CB on the books to discuss this and
other issues. I've got the two murkutu skins (one based on cdm and one on
gh) going -- and a new collection of images to incorporate. So we can
discuss skin building too.
