### ISSUE TITLE
Banner like SA?

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/collectionbuilder-gh#47]
@owikle @evanwill is there a reason we make the banner so small and unattractive? Looking at the docs, it would be simpler for all our banners to look/act the same.

**Comment by evanwill** [comment]
historically different because -GH is set up without the org logo and link concept. The other banners require a org logo and link to fill that extra space-- in the -GH context assuming everyone has an org and logo doesn't really make sense. 
I actually sort of prefer the simpler GH one though! 

But ultimately, we should just make one version that has a fall back if there is no org logo and link, and have the same thing in all versions. Could use a bit of a design freshen-up, maybe navbar better color scheme or something?

**Comment by evanwill** [comment]
single banner was ported to all templates
