### ISSUE TITLE
Objects not publishing

### ISSUE THREAD

**Issue by hhollow2** [CollectionBuilder/collectionbuilder-gh#57]
I apologize if this has been asked already. 

I'm using this guide: https://collectionbuilder.github.io/collectionbuilder-gh/about.html 

I've followed all the directions here, but the objects that I've uploaded are not being published. Only the objects from the template are showing up. I've compressed the image files for my own objects, double checked that the file names match, and adjusted file types, and still have not resolved the issue.

**Comment by evanwill** [comment]
@hhollow2 I assume you are talking about your collection [Holloway-Crystal-Collection](https://github.com/hhollow2/Holloway-Crystal-Collection)?

Looking at that repository I currently see two issues that are preventing the site from building (it looks like you are in process of trying to debug things, so sorry if this changes):

1. Your collection metadata is not set in [your _config.yml](https://github.com/hhollow2/Holloway-Crystal-Collection/blob/main/_config.yml)--see the [docs about setting metadata](https://collectionbuilder.github.io/cb-docs/docs/config/collection/). The current repository doesn't look like it has any metadata file added in _data right now (looks like maybe you deleted one?), you you might want to check the [metadata steps](https://collectionbuilder.github.io/cb-docs/docs/metadata/gh_metadata/) as well.
2. Your collection images are in the root of your repository--> they should be moved to the "objects" folder, since that is where the template is looking for the images. Any item images you want to include should always be in "objects" folder only.

Let me know if this helps! Good luck

**Comment by hhollow2** [comment]
@evanwill Oh my gosh, thank you so much! This completely fixed my page. This is for a project due in less than a week, you really saved me. Thank you, you rock!!

**Comment by evanwill** [comment]
Glad you got it sorted out @hhollow2 ! Let us know if you have more questions. 
p.s. what is the project for?
